spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false

  cache:
    type: simple

logging:
  level:
    org.springframework.web: WARN
    org.hibernate: WARN
    com.example.bankingsystem: DEBUG
    org.springframework.test: DEBUG

server:
  port: 0 # Random port for testing
